### PR TITLE
Add remaining tables

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
WIP

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn OK, I do believe this is all current relevant info - though have not exhaustively updated the ecephys ones yet

**Comment by garrettmflynn** [comment]
Created a PR that actually implements how to read these files (#5). Had to fix one of the JSON files because of a missing comma

**Comment by CodyCBakerPhD** [comment]
> Had to fix one of the JSON files because of a missing comma

The bane of all hand-typed JSON 😆

**Comment by CodyCBakerPhD** [comment]
LGTM, good to merge @garrettmflynn ?

**Review by garrettmflynn — APPROVED** [review]
Let's do it

**Pull request merged**
