### PR TITLE
Adding status column

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**

### CODE REVIEW

**Comment by garrettmflynn** [comment]
Looks good! Though I imagine, as we discussed, this may run over the desired width of the documentation `iframe`—as the status descriptors are longer than most other columns.

**Review by garrettmflynn — APPROVED** [review]

**Comment by CodyCBakerPhD** [comment]
I'll check it out via the iframe in a minute here once it deploys

**Comment by CodyCBakerPhD** [comment]
I'd say it looks pretty good on my screen, all the other columns adjusted in the way expected

Only looks weird when I artificially scrunch the window a super amount, but that's expected

**Comment by garrettmflynn** [comment]
Perfect!

**Pull request merged**
