### PR TITLE
Create test-pull-request-pages.yml

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
@garrettmflynn Hoping this makes it easier to test changes on PRs

### CODE REVIEW

**Comment by garrettmflynn** [comment]
Where do you visit to review the preview files?

**Comment by CodyCBakerPhD** [comment]
If it was working it would pop up with a link via the CI

**Comment by garrettmflynn** [comment]
Got it. And we can't run without merging in main, right?

I'm a bit skeptical of the _site targeting—though that might be fine given the actions you're working with. When I've seen that subfolder before, you have to ensure that files are built there, while we're usually just targeting the main folder.

Can always adjust in a follow-up.

**Comment by CodyCBakerPhD** [comment]
Ah, you're right - this was taken from https://github.com/NeurodataWithoutBorders/nwb_hackathons where they keep the built version on a different branch

**Comment by CodyCBakerPhD** [comment]
If you know a better way to test deployments on PRs let me know - I'd just like a way to test things before merging

**Review by garrettmflynn — APPROVED** [review]
Just simplified the workflow since we don't need a build step. Let's give it a go!

**Pull request merged**
